offline_homepage:
    pattern:  /
    defaults: { _controller: OfflineBundle:Default:index }
    methods:  [GET]

offline_index:
    pattern:  /index
    defaults: { _controller: OfflineBundle:Default:index }

send_user_feedback:
    pattern: /send_feedback
    defaults: { _controller: OfflineBundle:Default:sendUserFeedback}
    methods: [POST]

get_user_feedback:
    pattern: /get_feedback
    defaults: { _controller: OfflineBundle:Default:getUserFeedback}
    methods: [POST]