parameters:
#    offline.example.class: Sabrus\OfflineBundle\Example

services:
#    offline.example:
#        class: %offline.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
