<?php

namespace Sabrus\OfflineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserFeedBackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFeedBackRepository extends EntityRepository
{
    public function AddUserFeedBack($userfeedback)
    {
        $em = $this->getEntityManager();
        $em->persist($userfeedback);
        $em->flush();


    }
}
